name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.2
    - name: make
      run: c++ Termdle.cpp -std=c++11
